version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  versioning-strategy: lockfile-only
  ignore:
  - dependency-name: cross-fetch
    versions:
    - 3.0.6
    - 3.1.0
    - 3.1.1
    - 3.1.2
    - 3.1.3
  - dependency-name: xmldom
    versions:
    - 0.5.0
  - dependency-name: adal-node
    versions:
    - 0.2.2
  - dependency-name: bad-words
    versions:
    - 3.0.4
  - dependency-name: blipp
    versions:
    - 4.0.2
  - dependency-name: "@hapi/good-console"
    versions:
    - 9.0.1
  - dependency-name: "@hapi/good"
    versions:
    - 9.0.1
  - dependency-name: hapi-robots
    versions:
    - 3.2.2
  - dependency-name: "@hapi/subtext"
    versions:
    - 6.1.3
  - dependency-name: "@hapi/accept"
    versions:
    - 3.2.4
  - dependency-name: "@hapi/ammo"
    versions:
    - 3.1.2
  - dependency-name: lodash
    versions:
    - 4.17.20
    - 4.17.21
  - dependency-name: handlebars
    versions:
    - 4.7.6
    - 4.7.7
  - dependency-name: "@hapi/boom"
    versions:
    - 9.1.1
  - dependency-name: acorn
    versions:
    - 7.4.1
  - dependency-name: "@hapi/code"
    versions:
    - 8.0.2
  - dependency-name: "@hapi/lab"
    versions:
    - 22.0.5
  - dependency-name: hapi-router
    versions:
    - 5.1.0
  - dependency-name: pg
    versions:
    - 7.18.2
  - dependency-name: "@hapi/hapi"
    versions:
    - 18.4.1
