DELETE FROM registration;
DROP TABLE registration CASCADE;
DELETE FROM item;
DROP TABLE item CASCADE;
DELETE FROM choice;
DROP TABLE choice CASCADE;
DELETE FROM "group";
DROP TABLE "group" CASCADE;
DELETE FROM person;
DROP TABLE person CASCADE;
DELETE FROM address;
DROP TABLE address CASCADE;

